In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
data_path = './data/'

In [3]:
x = np.array([[1,2],[2,3],[3,4]])
print(x)

[[1 2]
 [2 3]
 [3 4]]


In [4]:
# mean
x.mean()
x.mean(axis=0)
x.mean(axis=1)

2.5

array([2., 3.])

array([1.5, 2.5, 3.5])

In [5]:
x = np.random.rand(2,3)
x

array([[0.30916875, 0.69275869, 0.46205801],
       [0.95599742, 0.03153568, 0.77394449]])

In [ ]:
# save data
