In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
x = np.arange(0,3,1)
y = np.array([False, True, False])

In [5]:
np.diff(x)

array([1, 1])

In [4]:
x
y
x[y]

array([0, 1, 2])

array([False,  True, False])

array([1])