In [7]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
x = np.array([[1,2],[3,4],[5,6]])

In [10]:
x[0,:]
x[1,:]
x[2,:]

array([1, 2])

array([3, 4])

array([5, 6])

In [12]:
x.mean(axis=1)
x.mean(axis=0)

array([1.5, 3.5, 5.5])

array([3., 4.])