In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
a = np.arange(0,10,2)
a
np.where(a>5)
# here np.where returns array's index

array([0, 2, 4, 6, 8])

(array([3, 4]),)

In [4]:
np.where(a>5, 2*a, a)

array([ 0,  2,  4, 12, 16])